- name: varaibales from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: "passing variables thro files"
    ansible.builtin.debug
      msg: "hello i am  learning {{course}} and trainer is {{trainer}} and duriation is {{duriation}}"
