- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: loopprocess
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - devops
    - aws
    - git

# - name: loops
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: print persons
#     ansible.builtin.package:
#       name: "{{item}}"
#       state: present # item is a default keyword
#     loop:
#     - git
#     - mysql
#     - postfix